// Generated by https://quicktype.io

export interface PokeResponse {
    count: number;
    next: string;
    previous: null;
    results: PokeItem[];
}

export interface PokeItem {
    name: string;
    url: string;
}
